In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
input_path = Path("../data/processed/adult_processed_v1_features_scaled.csv")

In [ ]:
df = pd.read_csv(input_path)

In [ ]:
df

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,income,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,...,native.country_Portugal,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia
0,3.316630,-0.538790,-0.439738,-0.147445,10.555814,-1.914161,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
1,1.184831,-0.467906,-2.400559,-0.147445,9.427915,-0.077734,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
2,0.195067,0.708645,-0.047574,-0.147445,9.427915,-0.077734,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
3,-0.337883,0.256222,-0.439738,-0.147445,9.106365,0.339636,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
4,-0.033340,-0.370964,-1.616231,-0.147445,9.106365,-0.077734,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30157,-1.251511,1.139203,-0.047574,-0.147445,-0.218586,-0.077734,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
30158,-0.870832,0.638972,0.736754,-0.147445,-0.218586,-0.244682,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
30159,0.118931,-0.335252,-0.439738,-0.147445,-0.218586,-0.077734,1,False,True,False,...,False,False,False,False,False,False,False,True,False,False
30160,1.489374,-0.358575,-0.439738,-0.147445,-0.218586,-0.077734,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False
30161,-1.251511,0.110705,-0.439738,-0.147445,-0.218586,-1.747213,0,False,True,False,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
X = df.drop('income', axis=1)
y = df['income']

In [ ]:
print(f"Форма признаков: {X.shape}")
print(f"Распределение классов:\n{y.value_counts(normalize=True) * 100}")

Форма признаков: (30162, 96)
Распределение классов:
income
0    75.107751
1    24.892249
Name: proportion, dtype: float64

In [ ]:
from imblearn.over_sampling import SMOTE

ModuleNotFoundError: No module named 'imblearn'

In [ ]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\georgiy\documents\adult_income_classifier\venv\lib\site-packages (0.13.0)
Requirement already satisfied: numpy<3,>=1.24.3 in c:\users\georgiy\documents\adult_income_classifier\venv\lib\site-packages (from imbalanced-learn) (2.2.6)
Requirement already satisfied: scipy<2,>=1.10.1 in c:\users\georgiy\documents\adult_income_classifier\venv\lib\site-packages (from imbalanced-learn) (1.15.3)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in c:\users\georgiy\documents\adult_income_classifier\venv\lib\site-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<1,>=0.1 in c:\users\georgiy\documents\adult_income_classifier\venv\lib\site-packages (from imbalanced-learn) (0.1.3)
Requirement already satisfied: joblib<2,>=1.1.1 in c:\users\georgiy\documents\adult_income_classifier\venv\lib\site-packages (from imbalanced-learn) (1.5.1)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\georgiy\documents\adult_income_classifier\venv\lib\site-packages (from imbalanced-learn) (3.6.0)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
smote = SMOTE(random_state=42)

In [ ]:
X_resampled, y_resampled = smote.fit_resample(X, y)

In [ ]:
print(f"Новая форма признаков: {X_resampled.shape}")
print("Новое распределение классов:")
print(y_resampled.value_counts(normalize=True) * 100)

Новая форма признаков: (45308, 96)
Новое распределение классов:
income
0    50.0
1    50.0
Name: proportion, dtype: float64

In [ ]:
df_balanced = pd.DataFrame(X_resampled, columns=X.columns)

In [ ]:
df_balanced

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,native.country_Portugal,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia
0,3.316630,-0.538790,-0.439738,-0.147445,10.555814,-1.914161,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
1,1.184831,-0.467906,-2.400559,-0.147445,9.427915,-0.077734,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
2,0.195067,0.708645,-0.047574,-0.147445,9.427915,-0.077734,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
3,-0.337883,0.256222,-0.439738,-0.147445,9.106365,0.339636,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,-0.033340,-0.370964,-1.616231,-0.147445,9.106365,-0.077734,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45303,0.507883,-0.802791,-0.439738,-0.147445,-0.218586,-0.077734,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
45304,1.461288,0.333465,-0.439738,0.110457,-0.218586,1.591745,False,True,True,False,...,False,False,False,False,False,False,False,True,False,False
45305,0.220682,-0.344527,-0.699963,-0.147445,-0.218586,-0.077734,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
45306,1.056800,0.668374,1.128918,-0.147445,-0.218586,0.757005,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
45307,0.215048,-0.587106,1.128918,-0.147445,-0.218586,0.442247,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
df_balanced['income'] = y_resampled

In [ ]:
output_path = Path("../data/processed/adult_balanced.csv")

In [ ]:
df_balanced.to_csv(output_path, index=False)